//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStarship", ReplyAction="http://tempuri.org/IService1/GetStarshipResponse")]
        SpaceYDTO.Starship GetStarship(int money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStarship", ReplyAction="http://tempuri.org/IService1/GetStarshipResponse")]
        System.Threading.Tasks.Task<SpaceYDTO.Starship> GetStarshipAsync(int money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSystem", ReplyAction="http://tempuri.org/IService1/GetSystemResponse")]
        SpaceYDTO.SpaceSystem GetSystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSystem", ReplyAction="http://tempuri.org/IService1/GetSystemResponse")]
        System.Threading.Tasks.Task<SpaceYDTO.SpaceSystem> GetSystemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendStarship", ReplyAction="http://tempuri.org/IService1/SendStarshipResponse")]
        SpaceYDTO.Starship SendStarship(SpaceYDTO.Starship starship, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendStarship", ReplyAction="http://tempuri.org/IService1/SendStarshipResponse")]
        System.Threading.Tasks.Task<SpaceYDTO.Starship> SendStarshipAsync(SpaceYDTO.Starship starship, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializeGame", ReplyAction="http://tempuri.org/IService1/InitializeGameResponse")]
        void InitializeGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InitializeGame", ReplyAction="http://tempuri.org/IService1/InitializeGameResponse")]
        System.Threading.Tasks.Task InitializeGameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SpaceClient.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SpaceClient.ServiceReference2.IService1>, SpaceClient.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpaceYDTO.Starship GetStarship(int money) {
            return base.Channel.GetStarship(money);
        }
        
        public System.Threading.Tasks.Task<SpaceYDTO.Starship> GetStarshipAsync(int money) {
            return base.Channel.GetStarshipAsync(money);
        }
        
        public SpaceYDTO.SpaceSystem GetSystem() {
            return base.Channel.GetSystem();
        }
        
        public System.Threading.Tasks.Task<SpaceYDTO.SpaceSystem> GetSystemAsync() {
            return base.Channel.GetSystemAsync();
        }
        
        public SpaceYDTO.Starship SendStarship(SpaceYDTO.Starship starship, string systemName) {
            return base.Channel.SendStarship(starship, systemName);
        }
        
        public System.Threading.Tasks.Task<SpaceYDTO.Starship> SendStarshipAsync(SpaceYDTO.Starship starship, string systemName) {
            return base.Channel.SendStarshipAsync(starship, systemName);
        }
        
        public void InitializeGame() {
            base.Channel.InitializeGame();
        }
        
        public System.Threading.Tasks.Task InitializeGameAsync() {
            return base.Channel.InitializeGameAsync();
        }
    }
}
